@extends('admin.layout')
@section('title','الرسوم وخطط الأقساط')
@section('content')
<link rel="stylesheet" href="{{ asset('css/finance.css') }}"><div class="finance-sheet">
<form class="finance-section" method="post" action="{{ route('finance.templates.store') }}">@csrf<h2>إنشاء رسوم</h2><div class="form-grid">
<label>الاسم<input name="name" value="{{ old('name') }}" required></label><label>نوع الرسوم<select name="fee_type_id">@foreach($types as $type)<option value="{{ $type->id }}" @selected(old('fee_type_id')==$type->id)>{{ $type->name }}</option>@endforeach</select></label><label>المبلغ بالدينار<input type="number" min="0.001" step="0.001" name="amount" value="{{ old('amount') }}" required></label>
<label>السنة الدراسية<select name="academic_year_id">@foreach($years as $year)<option value="{{ $year->id }}" @selected(old('academic_year_id')==$year->id)>{{ $year->name }}</option>@endforeach</select></label><label>الصف (اختياري)<select name="grade"><option value="">كل الصفوف</option>@foreach($classrooms->pluck('name')->unique() as $name)<option @selected(old('grade')===$name)>{{ $name }}</option>@endforeach</select></label>
<label>الشعبة (اختياري)<select name="classroom_id"><option value="">كل الشعب</option>@foreach($classrooms as $c)<option value="{{ $c->id }}" @selected(old('classroom_id')==$c->id)>{{ $c->name }} — {{ $c->section }}</option>@endforeach</select></label><label>طالب محدد (اختياري)<select name="student_id"><option value="">كل الطلاب المطابقين</option>@foreach($students as $s)<option value="{{ $s->id }}" @selected(old('student_id')==$s->id)>{{ $s->user->name }} — {{ $s->student_number }}</option>@endforeach</select></label>
<label>تاريخ الاستحقاق<input type="date" name="due_date" value="{{ old('due_date') }}" required></label><label>الإلزام<select name="required"><option value="1" @selected(old('required',1)==1)>إلزامية</option><option value="0" @selected(old('required')==='0')>اختيارية</option></select></label><label>الحالة<select name="active"><option value="1">نشطة</option><option value="0">غير نشطة</option></select></label><label>الوصف<textarea name="description">{{ old('description') }}</textarea></label></div>
<h3>الأقساط</h3><p>يمكن تركها فارغة لاعتماد دفعة واحدة. عند التقسيط يجب أن يساوي مجموع الأقساط مبلغ الرسوم.</p><div id="installments">@foreach(old('installments',[]) as $i=>$part)<div class="form-grid"><label>اسم القسط<input name="installments[{{ $i }}][name]" value="{{ $part['name']??'' }}" required></label><label>المبلغ<input type="number" step="0.001" min="0.001" name="installments[{{ $i }}][amount]" value="{{ $part['amount']??'' }}" required></label><label>الاستحقاق<input type="date" name="installments[{{ $i }}][due_date]" value="{{ $part['due_date']??'' }}" required></label><button type="button" onclick="this.parentElement.remove()">إزالة</button></div>@endforeach</div><div class="finance-actions"><button type="button" class="btn secondary" id="add-installment">إضافة قسط</button><button class="btn primary">حفظ الرسوم</button></div></form>
<section class="finance-section"><h2>الرسوم المعرفة</h2><div class="table-wrap"><table><thead><tr><th>الرسوم</th><th>المبلغ</th><th>الحالة</th><th>الطلاب المطابقون</th><th>الإجراء</th></tr></thead><tbody>@forelse($templates as $template)<tr><td>{{ $template->name }}<small> — {{ $template->required?'إلزامية':'اختيارية' }}</small><details><summary>تفاصيل الأقساط</summary>@foreach(json_decode($template->installment_plan,true) as $part)<p>{{ $part['name'] }} — {{ \App\Services\Money::format($part['amount_millimes']) }} — {{ $part['due_date'] }}</p>@endforeach</details></td><td>{{ \App\Services\Money::format($template->amount_millimes) }}</td><td>{{ $template->active?'نشطة':'غير نشطة' }}</td><td>{{ $template->target_count }}</td><td><form method="post" action="{{ route('finance.templates.apply',$template->id) }}">@csrf<button class="btn primary" @disabled(!$template->active) data-confirm="تطبيق هذه الرسوم على الطلاب المطابقين؟">تطبيق الرسوم</button></form><form method="post" action="{{ route('finance.templates.toggle',$template->id) }}">@csrf @method('patch')<input type="hidden" name="active" value="{{ $template->active?0:1 }}"><button class="btn secondary">{{ $template->active?'تعطيل':'تفعيل' }}</button></form></td></tr>@empty<tr><td colspan="5">لم تُضف رسوم بعد.</td></tr>@endforelse</tbody></table></div></section></div>
@endsection
@push('scripts')<script>let installmentIndex={{ count(old('installments',[])) }};document.getElementById('add-installment').onclick=()=>{const i=installmentIndex++,row=document.createElement('div');row.className='form-grid';row.innerHTML=`<label>اسم القسط<input name="installments[${i}][name]" required></label><label>المبلغ<input type="number" min="0.001" step="0.001" name="installments[${i}][amount]" required></label><label>الاستحقاق<input type="date" name="installments[${i}][due_date]" required></label><button type="button">إزالة</button>`;row.querySelector('button').onclick=()=>row.remove();document.getElementById('installments').append(row);};</script>@endpush
