@extends('teacher.layout')
@section('title', 'الدروس')
@section('subtitle', 'إدارة المحتوى التعليمي المنشور')
@section('actions')<a class="btn primary" href="{{ route('teacher.lessons.create') }}">إضافة درس جديد</a>@endsection
@section('content')
<form class="filters" method="get" action="{{ route('teacher.lessons.index') }}"><label><span class="label-head">الصف</span><select name="classroom_id"><option value="">كل الصفوف</option>@foreach($classrooms as $classroom)<option value="{{ $classroom->id }}" @selected(($filters['classroom_id'] ?? '') == $classroom->id)>{{ $classroom->name }} {{ $classroom->section }}</option>@endforeach</select></label><label><span class="label-head">تاريخ النشر</span><input type="date" name="published_at" value="{{ $filters['published_at'] ?? '' }}"></label><label><span class="label-head">الحالة</span><select name="status"><option value="">كل الحالات</option><option value="draft" @selected(($filters['status'] ?? '') === 'draft')>مسودة</option><option value="scheduled" @selected(($filters['status'] ?? '') === 'scheduled')>مجدول</option><option value="published" @selected(($filters['status'] ?? '') === 'published')>منشور</option><option value="cancelled" @selected(($filters['status'] ?? '') === 'cancelled')>ملغي</option></select></label><button class="btn primary" type="submit">تصفية</button><a class="btn secondary" href="{{ route('teacher.lessons.index') }}">إعادة ضبط</a></form>
<section class="attendance-summary status-summary" aria-label="ملخص الدروس"><article><span>مسودة</span><strong>{{ $lessonSummary['draft'] }}</strong></article><article><span>مجدولة</span><strong>{{ $lessonSummary['scheduled'] }}</strong></article><article><span>منشورة</span><strong>{{ $lessonSummary['published'] }}</strong></article><article><span>ملغاة</span><strong>{{ $lessonSummary['cancelled'] }}</strong></article></section>
<div class="table-wrap"><table><thead><tr><th>العنوان</th><th>الوحدة</th><th>المادة</th><th>الصف</th><th>الحالة</th><th>تاريخ النشر</th><th>المرفقات</th><th></th></tr></thead><tbody>
@forelse($lessons as $lesson)
@php($isPassed = $lesson->published_at?->isPast())
<tr><td>{{ $lesson->title }}</td><td>{{ $lesson->unit?->title ?: 'درس مستقل' }}</td><td>{{ $lesson->subject?->name }}</td><td>{{ $lesson->classroom?->name ?: '-' }}</td><td><span class="badge {{ $lesson->status === 'cancelled' ? 'status-cancelled' : ($lesson->status === 'published' ? 'active' : 'inactive') }}">{{ $lesson->status === 'cancelled' ? 'ملغي' : ($lesson->status === 'published' ? ($lesson->published_at?->isFuture() && ! $lesson->published_at?->isToday() ? 'مجدول' : 'منشور') : 'مسودة') }}</span></td><td>{{ $lesson->published_at?->format('Y-m-d H:i') ?: '-' }}</td><td>{{ $lesson->attachments->count() }}</td><td><a href="{{ route('teacher.lessons.edit', $lesson) }}">{{ $lesson->status === 'draft' ? 'متابعة' : 'تعديل' }}</a>@if($lesson->status !== 'cancelled' && $isPassed) · <form method="post" action="{{ route('teacher.lessons.cancel', $lesson) }}" style="display:inline">@csrf @method('patch')<button class="teacher-delete-action" type="submit" title="إلغاء الدرس" aria-label="إلغاء الدرس" data-confirm="هل أنت متأكد من إلغاء هذا الدرس؟">إلغاء</button></form>@endif · <form method="post" action="{{ route('teacher.lessons.destroy', $lesson) }}" style="display:inline">@csrf @method('delete')<button class="delete-column-btn teacher-delete-action" type="submit" title="حذف الدرس" aria-label="حذف الدرس" data-confirm="هل أنت متأكد من حذف الدرس؟">×</button></form></td></tr>
@empty <tr><td colspan="8">لا توجد دروس بعد.</td></tr>@endforelse
</tbody></table></div>{{ $lessons->links() }}
@endsection
