@extends('admin.layout')
@section('title','إعدادات المدرسة')
@section('content')
<form class="form-card" method="post" action="{{ route('admin.settings.update') }}" enctype="multipart/form-data">@csrf @method('put')
<div class="form-grid">
<label>اسم المدرسة<input name="school_name" value="{{ old('school_name',$settings['school_name']??'مدرسة النسبية') }}" required></label><label>الهاتف<input name="school_phone" value="{{ old('school_phone',$settings['school_phone']??'') }}"></label><label>البريد<input type="email" name="school_email" value="{{ old('school_email',$settings['school_email']??'') }}"></label><label>اسم المنصة<input value="افهمها وفهمني" disabled><small>اسم المنصة ثابت ولا يمكن تغييره.</small></label><label>شعار المدرسة<input type="file" name="school_logo" accept=".png,.jpg,.jpeg,.webp,.svg"><small>PNG أو JPG أو WEBP أو SVG، بحد أقصى 2MB.</small></label><label>المنطقة الزمنية<input name="timezone" value="{{ old('timezone',$settings['timezone']??'Africa/Tripoli') }}" required></label><label class="wide">العنوان<textarea name="school_address">{{ old('school_address',$settings['school_address']??'') }}</textarea></label>
</div>
<h2>لون الهوية</h2><div class="theme-options">@foreach(['#1239B3'=>'أزرق النسبية — أزرق ملكي','#078DB5'=>'أزرق افهمها — سماوي تقني','#008C95'=>'تركوازي — Teal','#00B978'=>'أخضر HEXA — أخضر تقني','#6D4AFF'=>'بنفسجي — Purple','#102A43'=>'داكن — Navy'] as $hex=>$label)<label class="theme-choice" style="--swatch:{{ $hex }}"><input type="radio" name="theme_color" value="{{ $hex }}" @checked(old('theme_color',$settings['theme_color']??'#008C95')===$hex)><span></span>{{ $label }} <code>{{ $hex }}</code></label>@endforeach</div>
<h2>عدد الحصص اليومية وأوقاتها</h2><p class="muted">حدد عدد الحصص، ثم بداية ونهاية كل حصة. تستخدم الجداول هذه الأوقات تلقائيًا.</p>
<div class="form-grid"><label>الاستراحة بعد الحصة<input type="number" min="1" max="11" name="break_after_period" value="{{ old('break_after_period',$settings['break_after_period']??3) }}" required id="break-after"></label><label>مدة الاستراحة بالدقائق<input type="number" min="5" max="120" name="break_duration_minutes" value="{{ old('break_duration_minutes',$settings['break_duration_minutes']??30) }}" required id="break-duration"></label></div><button type="button" class="btn secondary" id="apply-break">تطبيق الاستراحة على أوقات الحصص</button>
@foreach(['sunday'=>[0,'الأحد'],'monday'=>[1,'الإثنين'],'tuesday'=>[2,'الثلاثاء'],'wednesday'=>[3,'الأربعاء'],'thursday'=>[4,'الخميس']] as $day=>$dayInfo)
@php [$dayNumber,$dayLabel]=$dayInfo; @endphp <section class="card period-day" data-period-day><div class="form-grid"><label>عدد حصص {{ $dayLabel }}<input type="number" min="1" max="12" name="periods_{{ $day }}" value="{{ old('periods_'.$day,$settings['periods_'.$day]??($day==='thursday'?6:7)) }}" required data-period-count></label></div><div class="table-wrap"><table><thead><tr><th>الحصة</th><th>البداية</th><th>النهاية</th></tr></thead><tbody>
@for($period=1;$period<=12;$period++) @php
    $saved=$periodTimes->get($dayNumber.'-'.$period);
    $defaultStart=\Illuminate\Support\Carbon::createFromTime(8,30)->addMinutes(($period-1)*45+($period>3?30:0));
    $defaultEnd=$defaultStart->copy()->addMinutes(45);
@endphp
<tr data-period-row="{{ $period }}"><td>الحصة {{ $period }}</td><td><input type="time" name="period_times[{{ $dayNumber }}][{{ $period }}][starts_at]" value="{{ old("period_times.$dayNumber.$period.starts_at",$saved?->starts_at?substr($saved->starts_at,0,5):$defaultStart->format('H:i')) }}" required></td><td><input type="time" name="period_times[{{ $dayNumber }}][{{ $period }}][ends_at]" value="{{ old("period_times.$dayNumber.$period.ends_at",$saved?->ends_at?substr($saved->ends_at,0,5):$defaultEnd->format('H:i')) }}" required></td></tr>@endfor
</tbody></table></div></section>@endforeach
<h2>السنة الدراسية</h2><div class="form-grid"><label>السنة الدراسية<input name="academic_year_name" value="{{ old('academic_year_name',$currentYear?->name) }}" placeholder="2026/2027" required></label><label>بداية السنة<input type="date" name="academic_year_starts_at" value="{{ old('academic_year_starts_at',$currentYear?->starts_at?->format('Y-m-d')) }}" required></label><label>نهاية السنة<input type="date" name="academic_year_ends_at" value="{{ old('academic_year_ends_at',$currentYear?->ends_at?->format('Y-m-d')) }}" required></label></div>
<button class="btn primary">حفظ الإعدادات</button></form>
@endsection
@push('scripts')<script>document.querySelectorAll('[data-period-day]').forEach(day=>{const count=day.querySelector('[data-period-count]');const sync=()=>day.querySelectorAll('[data-period-row]').forEach(row=>row.hidden=Number(row.dataset.periodRow)>Number(count.value));count.addEventListener('input',sync);sync()});document.getElementById('apply-break').addEventListener('click',()=>{const after=Number(document.getElementById('break-after').value),duration=Number(document.getElementById('break-duration').value);document.querySelectorAll('[data-period-day]').forEach(day=>{const rows=[...day.querySelectorAll('[data-period-row]')];for(let i=1;i<rows.length;i++){const previousEnd=rows[i-1].querySelector('input[name$="[ends_at]"]').value;if(!previousEnd)continue;const [h,m]=previousEnd.split(':').map(Number),date=new Date(2000,0,1,h,m+(i===after?duration:0));const value=`${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`,start=rows[i].querySelector('input[name$="[starts_at]"]'),end=rows[i].querySelector('input[name$="[ends_at]"]'),oldStart=start.value,oldEnd=end.value;let length=45;if(oldStart&&oldEnd){const [sh,sm]=oldStart.split(':').map(Number),[eh,em]=oldEnd.split(':').map(Number);length=(eh*60+em)-(sh*60+sm)||45}start.value=value;const finish=new Date(2000,0,1,date.getHours(),date.getMinutes()+length);end.value=`${String(finish.getHours()).padStart(2,'0')}:${String(finish.getMinutes()).padStart(2,'0')}`}})})</script>@endpush
