@extends('admin.layout')
@section('title','المستخدمون')
@section('content')
<form class="filters"><input name="q" value="{{ request('q') }}" placeholder="الاسم أو البريد"><select name="role"><option value="">كل الأدوار</option>@foreach(['admin','supervisor','teacher','student','parent'] as $r)<option value="{{ $r }}">{{ $r }}</option>@endforeach</select><button class="btn secondary">بحث</button></form>
<div class="table-wrap"><table><thead><tr><th>الاسم</th><th>البريد</th><th>آخر دخول</th><th>الدور والحالة</th></tr></thead><tbody>
@foreach($users as $u)<tr><td>{{ $u->name }}</td><td>{{ $u->email }}</td><td>{{ $u->last_login_at?->format('Y-m-d H:i')?:'—' }}</td><td><form method="post" action="{{ route('admin.users.update',$u) }}">@csrf @method('patch')<select name="role">@foreach(['admin','supervisor','teacher','student','parent'] as $r)<option value="{{ $r }}" @selected($u->role===$r)>{{ $r }}</option>@endforeach</select><select name="status"><option value="active" @selected($u->status==='active')>نشط</option><option value="inactive" @selected($u->status==='inactive')>موقوف</option></select><button class="btn secondary">حفظ</button></form></td></tr>@endforeach
</tbody></table></div>{{ $users->links() }}
<section class="card"><h2>تكليفات المشرفين</h2>@forelse($users->where('role','supervisor') as $supervisor)<form method="post" action="{{ route('admin.users.update',$supervisor) }}">@csrf @method('patch')<input type="hidden" name="role" value="supervisor"><input type="hidden" name="status" value="{{ $supervisor->status }}"><strong>{{ $supervisor->name }}</strong>@foreach($classrooms as $classroom)<label><input type="checkbox" name="classroom_ids[]" value="{{ $classroom->id }}" @checked($supervisor->supervisedClassrooms->contains($classroom))> {{ $classroom->name }} {{ $classroom->section }}</label>@endforeach<button class="btn secondary">حفظ التكليفات</button></form>@empty<p>لا يوجد مشرفون في هذه الصفحة.</p>@endforelse</section>
@endsection
