<?php
namespace Tests\Feature;
use App\Models\AcademicYear; use App\Models\Classroom; use App\Models\Guardian; use App\Models\Student; use App\Models\User; use Illuminate\Foundation\Testing\RefreshDatabase; use Tests\TestCase;
class SupervisorAttendanceTest extends TestCase { use RefreshDatabase; private User $supervisor; private User $teacher; private User $parent; private Classroom $classroom; private Student $student;
 protected function setUp(): void { parent::setUp(); $year=AcademicYear::create(['name'=>'2026','starts_at'=>'2026-09-01','ends_at'=>'2027-06-01','is_current'=>true]); $this->classroom=Classroom::create(['name'=>'الأول','stage'=>'أساسي','section'=>'أ','academic_year_id'=>$year->id]); $this->supervisor=User::factory()->create(['role'=>'supervisor','status'=>'active']); $this->supervisor->supervisedClassrooms()->attach($this->classroom); $this->teacher=User::factory()->create(['role'=>'teacher','status'=>'active']); $this->parent=User::factory()->create(['role'=>'parent','status'=>'active']); $studentUser=User::factory()->create(['role'=>'student','status'=>'active']); $this->student=Student::create(['user_id'=>$studentUser->id,'student_number'=>'S-1','classroom_id'=>$this->classroom->id,'status'=>'active']); $guardian=Guardian::create(['user_id'=>$this->parent->id,'status'=>'active']); $guardian->students()->attach($this->student); }
 public function test_supervisor_can_create_and_update_one_daily_record(): void { $p=['date'=>'2026-09-10','classroom_id'=>$this->classroom->id,'records'=>[$this->student->id=>['status'=>'absent']]]; $this->actingAs($this->supervisor)->post('/supervisor/attendance',$p)->assertSessionHasNoErrors(); $p['records'][$this->student->id]=['status'=>'excused_absence','excuse_reason'=>'تقرير']; $this->post('/supervisor/attendance',$p)->assertSessionHasNoErrors(); $this->assertDatabaseCount('attendance_records',1); $this->assertDatabaseHas('attendance_records',['student_id'=>$this->student->id,'status'=>'excused_absence']); }
 public function test_teacher_and_parent_cannot_write_attendance(): void { foreach([$this->teacher,$this->parent] as $u){$this->actingAs($u)->post('/supervisor/attendance',[])->assertForbidden();} }
 public function test_supervisor_cannot_access_unassigned_student(): void { $other=Classroom::create(['name'=>'الثاني','stage'=>'أساسي','section'=>'ب','academic_year_id'=>$this->classroom->academic_year_id]); $s=Student::create(['user_id'=>User::factory()->create(['role'=>'student'])->id,'student_number'=>'S-2','classroom_id'=>$other->id]); $this->actingAs($this->supervisor)->get('/supervisor/students/'.$s->id)->assertForbidden(); }
 public function test_guardian_sees_only_visible_notes(): void { \App\Models\StudentNote::create(['student_id'=>$this->student->id,'supervisor_id'=>$this->supervisor->id,'type'=>'health','title'=>'داخلي','content'=>'سري','visibility'=>'internal']); \App\Models\StudentNote::create(['student_id'=>$this->student->id,'supervisor_id'=>$this->supervisor->id,'type'=>'general','title'=>'متاح','content'=>'متابعة','visibility'=>'guardian']); $this->actingAs($this->parent)->get('/parent/student-followup?student='.$this->student->id)->assertOk()->assertSee('متاح')->assertDontSee('داخلي'); }
}
