@extends('admin.layout')
@section('title','الإدارة المالية للطلاب')
@section('content')
<link rel="stylesheet" href="{{ asset('css/finance.css') }}"><div class="finance-sheet">
@if(auth()->user()->isAdmin())<div class="finance-actions"><a class="btn primary" href="{{ route('finance.templates') }}">الرسوم وخطط الأقساط</a><a class="btn secondary" href="{{ route('admin.accounts.index') }}">إعدادات وصول الطالب</a></div>@endif
<form class="filters"><input name="q" value="{{ request('q') }}" placeholder="اسم الطالب، الرقم، البريد، الهاتف أو ولي الأمر"><select name="academic_year_id"><option value="">جميع السنوات</option>@foreach($years as $year)<option value="{{ $year->id }}" @selected(request('academic_year_id')==$year->id)>{{ $year->name }}</option>@endforeach</select><select name="grade"><option value="">جميع الصفوف</option>@foreach($classrooms->pluck('name')->unique() as $grade)<option value="{{ $grade }}" @selected(request('grade')===$grade)>{{ $grade }}</option>@endforeach</select><select name="classroom_id"><option value="">جميع الصفوف والشعب</option>@foreach($classrooms as $classroom)<option value="{{ $classroom->id }}" @selected(request('classroom_id')==$classroom->id)>{{ $classroom->name }} — {{ $classroom->section }}</option>@endforeach</select><select name="status"><option value="">كل الحالات</option>@foreach($statuses as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select><button class="btn secondary">تصفية</button></form>
@if(auth()->user()->hasPermission('finance.reports'))<div class="finance-grid">@foreach(['total'=>'إجمالي الرسوم','discount'=>'الخصومات','net'=>'المتوقع تحصيله','paid'=>'المحصّل','remaining'=>'المستحق','overdue'=>'المتأخر'] as $key=>$label)<article>{{ $label }}<strong>{{ \App\Services\Money::format($dashboard[$key]) }}</strong></article>@endforeach<article>نسبة التحصيل<strong>{{ $dashboard['rate'] }}%</strong></article>@foreach(['paid','partially_paid','overdue'] as $status)<article>{{ $statuses[$status] }}<strong>{{ $counts[$status]??0 }} طالب</strong></article>@endforeach</div>@endif
<section class="finance-section"><h2>حسابات الطلاب</h2><div class="table-wrap"><table><thead><tr><th>الطالب</th><th>الرقم الدراسي</th><th>البريد</th><th>الحالة</th><th>المدفوع</th><th>المتبقي</th></tr></thead><tbody>@forelse($students as $student)<tr><td><a href="{{ route('finance.students.show',[$student,'academic_year_id'=>request('academic_year_id')]) }}">{{ $student->user->name }}</a><small> {{ $student->classroom?->name }}</small></td><td dir="ltr">{{ $student->student_number }}</td><td dir="ltr">{{ $student->user->email }}</td><td><span class="finance-badge {{ $student->financial_summary['status'] }}">{{ $statuses[$student->financial_summary['status']] }}</span></td><td>{{ \App\Services\Money::format($student->financial_summary['paid']) }}</td><td>{{ \App\Services\Money::format($student->financial_summary['remaining']) }}</td></tr>@empty<tr><td colspan="6">لا توجد حسابات مطابقة.</td></tr>@endforelse</tbody></table></div>{{ $students->links() }}</section>
<section class="finance-section"><h2>الاستحقاقات القادمة</h2>@forelse($upcoming as $row)<p><a href="{{ route('finance.students.show',$row->student_id) }}">ملف الطالب #{{ $row->student_id }}</a> — {{ $row->name }} — {{ $row->due_date }} — {{ \App\Services\Money::format($row->remaining_millimes) }}</p>@empty<p>لا توجد أقساط قادمة.</p>@endforelse</section>
@if(auth()->user()->hasPermission('finance.reports'))<div class="finance-grid">@foreach($charts as $title=>$values)<section class="finance-section"><h2>التحصيل حسب {{ $title }}</h2>@forelse($values as $label=>$value)<p>{{ $label }} — {{ \App\Services\Money::format($value) }}</p><div class="finance-bar" style="width:{{ $values->max()>0?round($value/$values->max()*100):0 }}%"></div>@empty<p>لا توجد مدفوعات.</p>@endforelse</section>@endforeach</div>@endif
@if(auth()->user()->isAdmin())<details class="finance-section"><summary>إضافة موظف مالي</summary><form method="post" action="{{ route('finance.officers.store') }}">@csrf<div class="form-grid"><label>الاسم<input name="name" required></label><label>البريد<input type="email" name="email" required></label><label>كلمة المرور (اتركها لاستخدام الرمز الافتراضي)<input type="password" name="password" autocomplete="new-password"></label><label>تأكيد كلمة المرور<input type="password" name="password_confirmation" autocomplete="new-password"></label></div><button class="btn primary">إنشاء الحساب</button></form></details>@endif
</div>@endsection
