@extends($layout)
@section('title','الحالة المالية للطالب')
@section('content')
<link rel="stylesheet" href="{{ asset('css/finance.css') }}"><div class="finance-sheet">
@if(isset($children))<div class="finance-no-print">@include('parent.partials.child-switcher')</div>@endif
<section class="finance-section"><h2>{{ $student->user->name }}</h2><p>الرقم الدراسي: <b dir="ltr">{{ $student->student_number }}</b> — الصف: {{ $student->classroom?->name }}</p><p>البريد المدرسي: <b dir="ltr">{{ $student->user->email }}</b></p><span class="finance-badge {{ $totals['status'] }}">{{ $statuses[$totals['status']] }}</span><p>المدرسة: {{ $schoolBranding['school_name'] }}</p></section>
<div class="finance-actions"><button class="btn secondary" onclick="window.print()">طباعة كشف الحساب</button><a class="btn primary" href="{{ request()->fullUrlWithQuery(['format'=>'pdf']) }}">تنزيل PDF</a></div><form class="finance-actions" method="get">@if(isset($selectedStudent))<input type="hidden" name="student" value="{{ $student->id }}">@endif<select name="academic_year_id"><option value="">كل السنوات الدراسية</option>@foreach($years as $year)<option value="{{ $year->id }}" @selected(request('academic_year_id')==$year->id)>{{ $year->name }}</option>@endforeach</select><button class="btn secondary">تصفية</button></form>
@include('finance.statement-data')
@if($manage && auth()->user()->hasPermission('finance.pay'))<form class="finance-section finance-no-print" method="post" action="{{ route('finance.students.pay',$student) }}">@csrf<input type="hidden" name="request_key" value="{{ old('request_key',(string)\Illuminate\Support\Str::uuid()) }}"><h2>تسجيل دفعة</h2><div class="form-grid"><label>الرسوم / القسط<select name="student_installment_id" required>@foreach($installments->where('remaining_millimes','>',0) as $i)<option value="{{ $i->id }}" @selected(old('student_installment_id')==$i->id)>{{ $i->fee_name }} / {{ $i->name }} — المتبقي {{ \App\Services\Money::format($i->remaining_millimes) }}</option>@endforeach</select></label><label>المبلغ بالدينار<input type="number" step="0.001" min="0.001" name="amount" value="{{ old('amount') }}" required></label><label>التاريخ<input type="date" name="paid_on" max="{{ now()->toDateString() }}" value="{{ old('paid_on',now()->toDateString()) }}" required></label><label>طريقة الدفع<select name="payment_method_id">@foreach($methods as $method)<option value="{{ $method->id }}" @selected(old('payment_method_id')==$method->id)>{{ $method->name }}</option>@endforeach</select></label><label>رقم المرجع<input name="reference" value="{{ old('reference') }}"></label><label>ملاحظات<textarea name="notes">{{ old('notes') }}</textarea></label></div><button class="btn primary" @disabled($installments->where('remaining_millimes','>',0)->isEmpty())>تسجيل وإصدار إيصال</button></form>@endif
@if($manage && auth()->user()->isAdmin())<details class="finance-section finance-no-print"><summary>اعتماد خصم أو إعفاء</summary><form method="post" action="{{ route('finance.students.discount',$student) }}">@csrf<div class="form-grid"><label>الرسوم<select name="student_fee_id">@foreach($fees as $fee)<option value="{{ $fee->id }}">{{ $fee->name }}</option>@endforeach</select></label><label>النوع<select name="type"><option value="fixed">خصم ثابت</option><option value="percentage">نسبة من الرسوم الأصلية</option><option value="scholarship">منحة بمبلغ ثابت</option><option value="waiver">إعفاء كامل من المتبقي</option></select></label><label>القيمة (تُترك فارغة للإعفاء)<input type="number" name="value" min="0" step="0.001"></label><label>السبب<textarea name="reason" required></textarea></label></div><button class="btn primary">اعتماد الخصم</button></form></details>@endif
</div>@endsection
