<!doctype html>
<html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>@yield('title') | افهمها وفهمني</title><link rel="stylesheet" href="{{ asset('css/admin.css') }}"><link rel="stylesheet" href="{{ asset('css/teacher-overrides.css') }}"></head>
<body class="teacher-portal"><a class="skip-link" href="#teacher-main">تجاوز إلى المحتوى</a><button class="menu-toggle" id="menu" aria-label="فتح القائمة" aria-controls="sidebar" aria-expanded="false">☰</button>
<aside class="sidebar" id="sidebar"><a class="logo" href="{{ route('teacher.dashboard') }}"><span class="brand-mark">AWF</span><span><b>افهمها وفهمني</b><small>بوابة المعلم</small></span></a>
<nav>@php($nav=['dashboard'=>['label'=>'الرئيسية','code'=>'01'],'classes'=>['label'=>'صفوفي','code'=>'02'],'students'=>['label'=>'الطلاب','code'=>'03'],'lessons'=>['label'=>'الدروس','code'=>'04'],'assignments'=>['label'=>'الواجبات','code'=>'05'],'exams'=>['label'=>'الاختبارات','code'=>'06'],'grades'=>['label'=>'الدرجات','code'=>'08'],'attendance'=>['label'=>'الحضور','code'=>'07']])
@foreach($nav as $key=>$item)
<a href="{{ route('teacher.'.$key.'.index') }}" class="{{ request()->routeIs('teacher.'.$key.'*')?'active':'' }}" @if(request()->routeIs('teacher.'.$key.'*')) aria-current="page" @endif><i>{{ $item['code'] }}</i><span>{{ $item['label'] }}</span></a>
@endforeach
</nav><div class="partner">الشريك التقني<br><b>HEXA.Tech</b></div></aside>
<div class="page"><header class="topbar"><form class="global-search"><input aria-label="بحث" placeholder="ابحث في المنصة..."></form><div class="account"><div class="teacher-account-menu"><button type="button" class="profile-link teacher-account-trigger" id="teacher-account-trigger" aria-expanded="false" aria-controls="teacher-account-dropdown">@if(auth()->user()->avatar_path)<img class="teacher-header-avatar" src="{{ route('teacher.profile.avatar', ['v' => auth()->user()->updated_at?->timestamp]) }}" alt="">@else<span class="teacher-header-avatar teacher-header-avatar--fallback">{{ mb_substr(auth()->user()->name, 0, 1) }}</span>@endif<span>{{ auth()->user()->name }}</span><span class="teacher-account-chevron" aria-hidden="true">⌄</span></button><div class="teacher-account-dropdown" id="teacher-account-dropdown" hidden><a href="{{ route('teacher.profile.edit') }}">الملف الشخصي</a><form method="post" action="{{ route('logout') }}">@csrf<button type="submit">تسجيل الخروج</button></form></div></div></div></header>
<main class="content" id="teacher-main" tabindex="-1">@if(session('success'))<div class="alert success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert error"><b>يرجى تصحيح الأخطاء:</b><ul>@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif
<div class="page-head"><div><p class="eyebrow">بوابة المعلم</p><h1>@yield('title')</h1><p class="muted">@yield('subtitle')</p></div>@yield('actions')</div>@yield('content')</main></div>
<script>const menu=document.getElementById('menu');const sidebar=document.getElementById('sidebar');menu.onclick=()=>{const open=sidebar.classList.toggle('open');menu.setAttribute('aria-expanded',open)};const accountTrigger=document.getElementById('teacher-account-trigger');const accountDropdown=document.getElementById('teacher-account-dropdown');accountTrigger?.addEventListener('click',()=>{const open=accountDropdown.hidden;accountDropdown.hidden=!open;accountTrigger.setAttribute('aria-expanded',String(open))});document.addEventListener('click',event=>{if(accountDropdown&&!accountDropdown.hidden&&!event.target.closest('.teacher-account-menu')){accountDropdown.hidden=true;accountTrigger.setAttribute('aria-expanded','false')}});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&accountDropdown&&!accountDropdown.hidden){accountDropdown.hidden=true;accountTrigger.setAttribute('aria-expanded','false');accountTrigger.focus()}});document.querySelectorAll('[data-confirm]').forEach(x=>x.onclick=e=>{if(!confirm(x.dataset.confirm))e.preventDefault()})</script>
@yield('scripts')
</body></html>
