<!doctype html>
<html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>بطاقة الطالب</title>
<style>body{font-family:dejavusans,Tahoma,Arial;color:#132d57;margin:0;padding:24px;background:#eef2f7}.card{overflow:hidden;border:1px solid #d4dbe5;border-radius:24px;background:#fff;max-width:760px;margin:auto;box-sizing:border-box;box-shadow:0 12px 32px #102c571c}.brand{position:relative;display:flex;align-items:center;gap:18px;min-height:112px;padding:18px 26px;color:#fff;background:linear-gradient(110deg,#123b79 0 69%,#0d2b59 69%);border-bottom:7px solid #f7931d}.brand:after{content:'';position:absolute;left:52%;bottom:-7px;width:34%;height:7px;background:#f7931d}.brand img{width:68px;height:68px;object-fit:contain;background:#fff;border-radius:50%;padding:5px}.brand h2{font-size:21px;margin:0 0 8px}.brand div{font-size:14px;color:#ffad3e;font-weight:bold}.title{margin-right:auto;font-size:22px!important;color:#fff!important}.body{display:grid;grid-template-columns:150px 1fr;gap:26px;padding:28px 30px 24px}.photo{height:175px;border:2px solid #d5dce7;border-radius:18px;background:linear-gradient(145deg,#f2f4f7,#dfe5ed);display:flex;align-items:center;justify-content:center;color:#738096;font-size:15px;font-weight:bold}.student-name{color:#123b79;font-size:29px;margin:0 0 19px}.row{display:flex;align-items:center;gap:16px;padding:10px 0;border-bottom:1px solid #e4e8ee;font-size:14px}.label{color:#647188;min-width:125px;font-weight:bold}.value{color:#132d57;font-weight:bold;overflow-wrap:anywhere}.qr{width:86px;height:86px;margin-top:20px}.actions{text-align:center;margin-top:18px}button,a{background:#123b79;color:#fff;border:0;border-radius:8px;padding:9px 14px;text-decoration:none;font-size:12px;margin:3px}@media print{body{padding:0;background:#fff}.actions{display:none}}@media(max-width:600px){.body{grid-template-columns:1fr}.photo{width:150px}.title{font-size:16px!important}}</style></head>
<body><article class="card"><div class="brand">@if($pdfLogo??null)<img src="{{ $pdfLogo }}" alt="شعار المدرسة">@elseif($schoolBranding['logo'] && !($pdf??false))<img src="{{ asset('storage/'.$schoolBranding['logo']) }}" alt="شعار المدرسة">@endif<div><h2>{{ $schoolBranding['school_name'] }}</h2><div>التعليم كما يجب أن يكون</div></div><div class="title">بطاقة الطالب</div></div><div class="body"><div><div class="photo">صورة الطالب</div>@if($student->qr_image??null)<img class="qr" src="{{ $student->qr_image }}" alt="QR">@endif</div><div><h1 class="student-name">{{ $student->user->name }}</h1>
<div class="row"><span class="label">الرقم الدراسي</span><b class="value" dir="ltr">{{ $student->student_number }}</b></div>
<div class="row"><span class="label">البريد الإلكتروني</span><b class="value" dir="ltr">{{ $student->user->email }}</b></div>
<div class="row"><span class="label">الصف</span><b class="value">{{ $student->classroom?->name }} {{ $student->classroom?->section }}</b></div>
<div class="row"><span class="label">العام الدراسي</span><b class="value">{{ $student->classroom?->academicYear?->name ?: '—' }}</b></div>
<div class="row"><span class="label">رقم الهوية</span><b class="value" dir="ltr">NS-{{ $student->student_number }}</b></div></div></div>
@if(!($pdf??false))<div class="actions"><button onclick="window.print()">طباعة</button><a href="{{ request()->fullUrlWithQuery(['format'=>'pdf']) }}">تنزيل PDF</a></div>@endif
</article></body></html>
